name: ml-fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.1
  - requests
  - pip
  - fastapi
  - uvicorn
  - jupyter
  - jupyterlab
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pip:
      - pytest
      - flake8
      - setuptools
      - pylint
      - httpx
      - dvc