name: Python Tests and Linting

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}

    env:
      SETUP_PYTHON_VERSION: '2'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '20.x'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8

    - name: Run pytest
      run: |
        pytest

    - name: Run flake8
      run: |
        flake8
