name: Python Tests and Linting

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

      # Specify Node.js version for this step
      env:
        NODE_VERSION: '20'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8

    - name: Run pytest
      run: |
        pytest

    - name: Run flake8
      run: |
        flake8
