name: Python Tests and Linting

on:
  push:
    branches:
      - main  #Default branch if it's not main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.12.1'  # Desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8

    - name: Run pytest
      run: |
        pytest

    - name: Run flake8
      run: |
        flake8
